### ISSUE TITLE
V2 is 35 times bigger than V1

### ISSUE THREAD

**Issue by tconfrey** [orgapp/orgajs#83]
I use orga in my BrainTool chrome extension and package all the files into a single bundle using [Browserify](http://browserify.org/). The bundle I created for v1 is 20KB but the V2 version is 677KB! I understand the new version uses Unified and so incorporate a whole new set of libraries but still the size increase is extreme. Is there any easy way to remove unneeded dependencies, or any other advice on making the size more manageable? (NB the [Tinyify](https://github.com/browserify/tinyify) plugin drops the size quite a bit but its still a dozen times as big as before).

Thanks for your work on orga!

**Comment by xiaoxinghu** [comment]
Thanks for the feedback. Found the offenders, will kill them shortly after my current big work (webpack loader and jsx support).

**Comment by xiaoxinghu** [comment]
Hi @tconfrey, I have removed 2 of the biggest dependencies from orga (xregexp and luxon). 
- [xregexp](https://xregexp.com/) is for easy timestamp parsing, I have [implemented my own logic](https://github.com/orgapp/orgajs/commit/4c2e3b0aff58561ea43958f63a5f7ffe1935572a) there without heavily rely on fancy regex, so `xregexp` can be removed.
- [luxon](https://moment.github.io/luxon/) is for date processing since not all of us live in UTC timezone, and it's pretty hard to deal with timezone in javascript without the help of a library. I used luxon for it, then I found [date-fns-tz](https://github.com/marnusw/date-fns-tz) which is a smaller package which only deals with timezone. So I [switched to it](https://github.com/orgapp/orgajs/commit/00511267efe3f1af1d79e4f884a1e4466f0a4b12).

That significantly reduced the package size. Another reason for the increase of the package is probably due to switching to TypeScript. TS generates map files and type definition files, which are useful for consumption of the package as a dependency and error checking. It could be easily shaken off by some minify tools (I haven't tried it myself though). Also, the generated js files might be a little bit more verbose than it uses to. 

It's released at v2.4.6, please revisit the issue. Let me know if you have more ideas on how to optimize it.

**Comment by tconfrey** [comment]
Looks good at 3x smaller than it was before. I tried some further minification tools but ran into issues and decided this is close enough. Thanks for addressing this @xiaoxinghu
